name: 'ZIP SFTP Upload'
description: 'Upload repo as a zip/archive to SFTP server'
inputs:
  package_name:
    description: 'name of the zip file'
    required: true
  username:
    description: 'username'
    required: true
  server:
    description: 'your sftp server'
    required: true
  port:
    description: 'your sftp server port'
    required: true
  ssh_private_key:
    description: 'you can copy private_key from your *.pem file, keep format'
    required: true
  local_path:
    description: 'will put all file under this path. e.g ./*'
    required: true
  remote_path:
    description: 'release file will deploy to this directory'
    required: true
  script_path:
    description: 'shell script to run in addition to deploy'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'upload-cloud'
  color: 'red'
