name: 'Release Upload SFTP'
description: 'Upload release zip file to SFTP server'
inputs:
  package_name:
    description: 'name of the zip file'
    required: true
  username:
    description: 'username'
    required: true
  server:
    description: 'your sftp server'
    required: true
  port:
    description: 'your sftp server port, default to 22'
    required: true
    default: "22"
  ssh_private_key:
    description: 'you can copy private_key from your *.pem file, keep format'
    required: true
  local_path:
    description: 'will put all file under this path'
    required: true
    default: ./*
  remote_path:
    description: 'release file will deploy to this directory'
    required: true
    default: /
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'upload-cloud'
  color: 'red'
